# Generated by Django 6.0.4 on 2026-04-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考试名称')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('ongoing', '进行中'), ('ended', '已结束')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'db_table': 'tb_exam',
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(verbose_name='学生ID')),
                ('answer', models.TextField(verbose_name='答案')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='得分')),
                ('is_auto', models.BooleanField(default=False, verbose_name='是否自动批改')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'tb_exam_answer',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='试卷名称')),
                ('total_score', models.IntegerField(default=0, verbose_name='总分')),
                ('duration', models.IntegerField(default=90, verbose_name='时长(分钟)')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'db_table': 'tb_paper',
            },
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'db_table': 'tb_paper_question',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=100, verbose_name='章节')),
                ('type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('blank', '填空题'), ('essay', '问答题')], max_length=20, verbose_name='题型')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='选项')),
                ('answer', models.TextField(verbose_name='答案')),
                ('analysis', models.TextField(blank=True, verbose_name='解析')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], max_length=10, verbose_name='难度')),
                ('score', models.IntegerField(default=5, verbose_name='分值')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'tb_question',
            },
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(verbose_name='学生ID')),
                ('total_score', models.IntegerField(verbose_name='总分')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='排名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'tb_score_record',
            },
        ),
    ]
