# Generated by Django 6.0.4 on 2026-04-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='备注内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '课堂备注',
                'verbose_name_plural': '课堂备注',
                'db_table': 'tb_class_note',
            },
        ),
        migrations.CreateModel(
            name='MeetingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='参会用户名')),
                ('role', models.CharField(choices=[('host', '主持人'), ('participant', '参会者')], max_length=20, verbose_name='角色')),
                ('join_time', models.DateTimeField(verbose_name='入会时间')),
                ('leave_time', models.DateTimeField(blank=True, null=True, verbose_name='离会时间')),
                ('duration', models.IntegerField(default=0, verbose_name='参会时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '参会记录',
                'verbose_name_plural': '参会记录',
                'db_table': 'tb_meeting_record',
            },
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(blank=True, max_length=50, verbose_name='腾讯会议ID')),
                ('meeting_password', models.CharField(blank=True, max_length=20, verbose_name='会议密码')),
                ('join_url', models.CharField(blank=True, max_length=500, verbose_name='入会链接')),
                ('host_key', models.CharField(blank=True, max_length=20, verbose_name='主持人密钥')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('ongoing', '进行中'), ('ended', '已结束')], default='pending', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '会议室',
                'verbose_name_plural': '会议室',
                'db_table': 'tb_meeting_room',
            },
        ),
        migrations.CreateModel(
            name='PlaybackFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=500, verbose_name='回放地址')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('duration', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('ready', '可用'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('view_permission', models.CharField(choices=[('all', '所有人'), ('teacher', '教师'), ('student', '学生'), ('none', '不可查看')], default='teacher', max_length=20, verbose_name='查看权限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '回放文件',
                'verbose_name_plural': '回放文件',
                'db_table': 'tb_playback_file',
            },
        ),
        migrations.CreateModel(
            name='RecordingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(blank=True, max_length=50, verbose_name='录制ID')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('recording', '录制中'), ('transcoding', '转码中'), ('ready', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('file_url', models.CharField(blank=True, max_length=500, verbose_name='文件URL')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('duration', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '录制任务',
                'verbose_name_plural': '录制任务',
                'db_table': 'tb_recording_task',
            },
        ),
    ]
