# Generated by Django 6.0.4 on 2026-04-07 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('edu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_notes', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='classnote',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_notes', to='edu.schedule', verbose_name='课次'),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_records', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room', to='edu.schedule', verbose_name='课次'),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='meeting_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='classroom.meetingroom', verbose_name='会议室'),
        ),
        migrations.AddField(
            model_name='recordingtask',
            name='meeting_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_tasks', to='classroom.meetingroom', verbose_name='会议室'),
        ),
        migrations.AddField(
            model_name='playbackfile',
            name='recording_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_files', to='classroom.recordingtask', verbose_name='录制任务'),
        ),
    ]
