# Generated by Django 6.0.4 on 2026-04-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='课程编码')),
                ('description', models.TextField(blank=True, verbose_name='课程描述')),
                ('cover', models.CharField(blank=True, max_length=500, verbose_name='封面图')),
                ('total_hours', models.IntegerField(verbose_name='总课时')),
                ('duration', models.IntegerField(default=90, verbose_name='单次课时长(分钟)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('status', models.CharField(choices=[('active', '在售'), ('archived', '已下架')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'tb_course',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HoursFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deduct', '扣课'), ('gift', '赠送'), ('freeze', '冻结'), ('refund', '退款'), ('unfreeze', '解冻')], max_length=20, verbose_name='类型')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='课时数量')),
                ('balance_before', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='变动前余额')),
                ('balance_after', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='变动后余额')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '课时流水',
                'verbose_name_plural': '课时流水',
                'db_table': 'tb_hours_flow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('student', '学生请假'), ('teacher', '教师请假')], max_length=20, verbose_name='类型')),
                ('reason', models.TextField(verbose_name='原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '请假记录',
                'verbose_name_plural': '请假记录',
                'db_table': 'tb_leave_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RescheduleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('adjust', '调课'), ('reschedule', '补课'), ('supplement', '代课')], max_length=20, verbose_name='类型')),
                ('reason', models.TextField(verbose_name='原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '调课记录',
                'verbose_name_plural': '调课记录',
                'db_table': 'tb_reschedule_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='上课日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='教室')),
                ('status', models.CharField(choices=[('scheduled', '已排课'), ('cancelled', '已取消'), ('completed', '已完成')], default='scheduled', max_length=20, verbose_name='状态')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '排课',
                'verbose_name_plural': '排课',
                'db_table': 'tb_schedule',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='小结名称')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '小结',
                'verbose_name_plural': '小结',
                'db_table': 'tb_section',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('avatar', models.CharField(blank=True, max_length=500, verbose_name='头像URL')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=10, null=True, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('grade', models.CharField(max_length=20, verbose_name='年级')),
                ('school', models.CharField(blank=True, max_length=100, verbose_name='学校')),
                ('parent_name', models.CharField(max_length=50, verbose_name='家长姓名')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='家长手机')),
                ('status', models.CharField(choices=[('active', '在读'), ('inactive', '休学'), ('graduated', '毕业'), ('withdrawn', '退学')], default='active', max_length=20, verbose_name='状态')),
                ('enrollment_date', models.DateField(verbose_name='入学日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'tb_student',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentHoursAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='总课时')),
                ('used_hours', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='已用课时')),
                ('frozen_hours', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='冻结课时')),
                ('gift_hours', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='赠送课时')),
                ('status', models.CharField(choices=[('active', '正常'), ('frozen', '冻结'), ('expired', '过期')], default='active', max_length=20, verbose_name='状态')),
                ('expire_date', models.DateField(verbose_name='过期日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生课时账户',
                'verbose_name_plural': '学生课时账户',
                'db_table': 'tb_student_hours_account',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='科目名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='科目编码')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
                'db_table': 'tb_subject',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('avatar', models.CharField(blank=True, max_length=500, verbose_name='头像URL')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=10, null=True, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('education', models.CharField(max_length=20, verbose_name='学历')),
                ('major', models.CharField(max_length=50, verbose_name='专业')),
                ('certification', models.CharField(blank=True, max_length=50, verbose_name='证书')),
                ('status', models.CharField(choices=[('active', '在职'), ('resigned', '离职')], default='active', max_length=20, verbose_name='状态')),
                ('hire_date', models.DateField(verbose_name='入职日期')),
                ('salary_type', models.CharField(choices=[('hourly', '按课时'), ('fixed', '固定工资')], max_length=20, verbose_name='薪资类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 'tb_teacher',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='章节名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='edu.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'db_table': 'tb_chapter',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('hours', models.IntegerField(verbose_name='总课时')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('valid_days', models.IntegerField(default=365, verbose_name='有效期(天)')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('courses', models.ManyToManyField(related_name='packages', to='edu.course', verbose_name='包含课程')),
            ],
            options={
                'verbose_name': '课程包',
                'verbose_name_plural': '课程包',
                'db_table': 'tb_course_package',
            },
        ),
        migrations.CreateModel(
            name='EduClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='班级编码')),
                ('max_students', models.IntegerField(default=20, verbose_name='最大人数')),
                ('status', models.CharField(choices=[('open', '开班'), ('closed', '结课')], default='open', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(verbose_name='开班日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结课日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='edu.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'tb_class',
            },
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(verbose_name='入班日期')),
                ('status', models.CharField(choices=[('studying', '在读'), ('graduated', '已结课'), ('removed', '已移除')], default='studying', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edu_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='edu.educlass', verbose_name='班级')),
            ],
            options={
                'verbose_name': '班级学生',
                'verbose_name_plural': '班级学生',
                'db_table': 'tb_class_student',
            },
        ),
    ]
