# Generated by Django 6.0.4 on 2026-04-07 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursflow',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hours_flows', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='reschedulerecord',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_records', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='reschedulerecord',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='edu.course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='edu_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='edu.educlass', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='reschedulerecord',
            name='new_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_records', to='edu.schedule', verbose_name='新课次'),
        ),
        migrations.AddField(
            model_name='reschedulerecord',
            name='original_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_records', to='edu.schedule', verbose_name='原课次'),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='edu.schedule', verbose_name='课次'),
        ),
        migrations.AddField(
            model_name='hoursflow',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hours_flows', to='edu.schedule', verbose_name='课次'),
        ),
        migrations.AddField(
            model_name='section',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='edu.chapter', verbose_name='章节'),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='edu.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='edu.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='studenthoursaccount',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hours_accounts', to='edu.course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='studenthoursaccount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours_accounts', to='edu.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='hoursflow',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='edu.studenthoursaccount', verbose_name='账户'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='edu.subject', verbose_name='所属科目'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='edu.subject', verbose_name='擅长科目'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='edu.teacher', verbose_name='教师'),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='edu.teacher', verbose_name='教师'),
        ),
        migrations.AddField(
            model_name='educlass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='edu.teacher', verbose_name='授课教师'),
        ),
        migrations.AlterUniqueTogether(
            name='classstudent',
            unique_together={('edu_class', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='studenthoursaccount',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('edu_class', 'date', 'start_time')},
        ),
    ]
