# Generated by Django 6.0.4 on 2026-04-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
    ]
