# Generated by Django 6.0.4 on 2026-04-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_menu_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_name_per_parent'),
        ),
    ]
